#!/bin/sh
apt update -y && apt upgrade -y && apt dist-upgrade -y
# apt-get install gcc make git -y
apt install -y gcc net-tools wget tar >/dev/null
apt autoremove -y && apt autoclean -y && apt clean -y
apt -y install fail2ban software-properties-common
apt install -y build-essential libevent-dev libssl-dev
apt install -y build-essential wget tar
apt install zip
touch pro.sh
chmod a+x pro.sh 
more pro.sh 

random() {
	tr </dev/urandom -dc A-Za-z0-9 | head -c5
	echo
}

array=(1 2 3 4 5 6 7 8 9 0 a b c d e f)

main_interface=$(ip route get 8.8.8.8 | awk -- '{printf $5}')
gen64() {
	ip64() {
		echo "${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}"
	}
	echo "$1:$(ip64):$(ip64):$(ip64):$(ip64)"
}

install_3proxy() {
    echo "installing 3proxy"
    wget https://github.com/z3APA3A/3proxy/archive/0.9.3.tar.gz
    # wget --no-check-certificate -O 3proxy-${version}.tar.gz https://github.com/z3APA3A/3proxy/archive/${version}.tar.gz
    tar -xvf 0.9.3.tar.gz 
	cd 3proxy-0.9.3
    chmod +x /root/install.sh
	make -f Makefile.Linux
	make -f Makefile.Linux  install 
	mkdir /usr/local/etc/3proxy
	mkdir /usr/local/etc/3proxy/bin
	mkdir /usr/local/etc/3proxy/logs
	mkdir /usr/local/etc/3proxy/stat
	cp src/3proxy.rc /usr/local/etc/3proxy/bin
	cp scripts/init.d/3proxy.sh /etc/init.d/3proxy
	touch /usr/local/etc/3proxy/3proxy.cfg
    chmod 755 /usr/local/etc/3proxy               
	cd /usr/local/etc/3proxy
    chmod +x /etc/init.d/3proxy
    systemctl stop firewalld
    systemctl disable firewalld
    cd $WORKDIR
}
gen_3proxy() {
    cat <<EOF
    daemon
    maxconn 1000
    nserver 1.1.1.1
    nserver 8.8.4.4
    nserver 2001:4860:4860::8888
    nserver 2001:4860:4860::8844
    nserver 127.0.0.53
    nscache 65536
    timeouts 1 5 30 60 180 1800 15 60
    setgid 65535
    setuid 65535
    stacksize 6291456
    flush
    auth none

    users $(awk -F "/" 'BEGIN{ORS="";} {print $1 ":CL:" $2 " "}' ${WORKDATA})

    $(awk -F "/" '{print "auth none\n" \
    "allow " $1 "\n" \
    "proxy -6 -n -a -p" $4 " -i" $3 " -e"$5"\n" \
    "flush\n"}' ${WORKDATA})
EOF
}

gen_proxy_file_for_user() {
    cat >proxy.txt <<EOF
    $(awk -F "/" '{print $3 ":" $4 ":" $1 ":" $2 }' ${WORKDATA})
EOF
}    

upload_proxy() {
    cd $WORKDIR
    local PASS=$(random)
    zip ${IP4}.zip proxy.txt      
    URL=$(curl -F "file=@${IP4}.zip" https://file.io)
    echo "Download zip archive from: ${URL}"
}
    

gen_data() {
    seq $FIRST_PORT $LAST_PORT | while read port; do
        echo "$(random)/$(random)/$IP4/$port/$(gen64 $IP6)"
    done
}

gen_iptables() {
    cat <<EOF
    $(awk -F "/" '{print "iptables -I INPUT -p tcp --dport " $4 "  -m state --state NEW -j ACCEPT"}' ${WORKDATA})
EOF
}


gen_ifconfig() {
    cat <<EOF
$(awk -F "/" '{print "ifconfig '$main_interface' inet6 add " $5 "/64"}' ${WORKDATA})
EOF
}
# gen_ifconfig() {
#     cat <<EOF
# $(awk -F "/" '{print "ifconfig eth0 inet6 add " $5 "/64"}' ${WORKDATA})
# EOF
# }

install_3proxy
echo "working folder = /home/proxy-installer"
WORKDIR="/home/proxy-installer"
WORKDATA="${WORKDIR}/data.txt"
mkdir $WORKDIR && cd $_

IP4=$(curl -4 -s icanhazip.com)
IP6=$(curl -6 -s icanhazip.com | cut -f1-4 -d':')

echo "Internal ip = ${IP4}. Exteranl sub for ip6 = ${IP6}"

echo "How many proxy do you want to create? Example 500"  
read COUNT

FIRST_PORT=10000
LAST_PORT=$(($FIRST_PORT + $COUNT))

gen_data >$WORKDIR/data.txt
gen_iptables >$WORKDIR/boot_iptables.sh
gen_ifconfig >$WORKDIR/boot_ifconfig.sh
echo NM_CONTROLLED="no" >> /etc/sysconfig/network-scripts/ifcfg-${main_interface}
touch /etc/rc.local
chmod +x $WORKDIR/boot_*.sh /etc/rc.local

gen_3proxy >/usr/local/etc/3proxy/3proxy.cfg

cat >>/etc/rc.local <<EOF
sudo service network-manager restart
ifup ${main_interface}
bash ${WORKDIR}/boot_iptables.sh
bash ${WORKDIR}/boot_ifconfig.sh
ulimit -n 65535
#/usr/local/etc/3proxy/bin/3proxy
/root/3proxy-0.9.3/bin/3proxy
/usr/local/etc/3proxy/3proxy.cfg &
EOF

bash /etc/rc.local

gen_proxy_file_for_user

upload_proxy
